-- CreateTable
CREATE TABLE `TobaccoMember` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `villageId` INTEGER NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `smokeType` VARCHAR(191) NOT NULL,
    `y1Money` BOOLEAN NOT NULL DEFAULT false,
    `y1MoneyText` TEXT NULL,
    `y1Property` BOOLEAN NOT NULL DEFAULT false,
    `y1PropertyText` TEXT NULL,
    `y1Family` BOOLEAN NOT NULL DEFAULT false,
    `y1FamilyText` TEXT NULL,
    `y1Health` BOOLEAN NOT NULL DEFAULT false,
    `y1HealthText` TEXT NULL,
    `y1Work` BOOLEAN NOT NULL DEFAULT false,
    `y1WorkText` TEXT NULL,
    `y1Accepted` BOOLEAN NOT NULL DEFAULT false,
    `y1AcceptedText` TEXT NULL,
    `y1Other` BOOLEAN NOT NULL DEFAULT false,
    `y1OtherText` TEXT NULL,
    `y2Money` BOOLEAN NOT NULL DEFAULT false,
    `y2MoneyText` TEXT NULL,
    `y2Property` BOOLEAN NOT NULL DEFAULT false,
    `y2PropertyText` TEXT NULL,
    `y2Family` BOOLEAN NOT NULL DEFAULT false,
    `y2FamilyText` TEXT NULL,
    `y2Health` BOOLEAN NOT NULL DEFAULT false,
    `y2HealthText` TEXT NULL,
    `y2Work` BOOLEAN NOT NULL DEFAULT false,
    `y2WorkText` TEXT NULL,
    `y2Accepted` BOOLEAN NOT NULL DEFAULT false,
    `y2AcceptedText` TEXT NULL,
    `y2Other` BOOLEAN NOT NULL DEFAULT false,
    `y2OtherText` TEXT NULL,
    `y3Money` BOOLEAN NOT NULL DEFAULT false,
    `y3MoneyText` TEXT NULL,
    `y3Property` BOOLEAN NOT NULL DEFAULT false,
    `y3PropertyText` TEXT NULL,
    `y3Family` BOOLEAN NOT NULL DEFAULT false,
    `y3FamilyText` TEXT NULL,
    `y3Health` BOOLEAN NOT NULL DEFAULT false,
    `y3HealthText` TEXT NULL,
    `y3Work` BOOLEAN NOT NULL DEFAULT false,
    `y3WorkText` TEXT NULL,
    `y3Accepted` BOOLEAN NOT NULL DEFAULT false,
    `y3AcceptedText` TEXT NULL,
    `y3Other` BOOLEAN NOT NULL DEFAULT false,
    `y3OtherText` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `TobaccoMember_villageId_idx`(`villageId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `TobaccoMember` ADD CONSTRAINT `TobaccoMember_villageId_fkey` FOREIGN KEY (`villageId`) REFERENCES `Village`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
