-- AlterTable
ALTER TABLE `AlcoholMember` ADD COLUMN `y1AcceptedText` TEXT NULL,
    ADD COLUMN `y1FamilyText` TEXT NULL,
    ADD COLUMN `y1HealthText` TEXT NULL,
    ADD COLUMN `y1MoneyText` TEXT NULL,
    ADD COLUMN `y1PropertyText` TEXT NULL,
    ADD COLUMN `y1WorkText` TEXT NULL,
    ADD COLUMN `y2AcceptedText` TEXT NULL,
    ADD COLUMN `y2FamilyText` TEXT NULL,
    ADD COLUMN `y2HealthText` TEXT NULL,
    ADD COLUMN `y2MoneyText` TEXT NULL,
    ADD COLUMN `y2PropertyText` TEXT NULL,
    ADD COLUMN `y2WorkText` TEXT NULL,
    ADD COLUMN `y3AcceptedText` TEXT NULL,
    ADD COLUMN `y3FamilyText` TEXT NULL,
    ADD COLUMN `y3HealthText` TEXT NULL,
    ADD COLUMN `y3MoneyText` TEXT NULL,
    ADD COLUMN `y3PropertyText` TEXT NULL,
    ADD COLUMN `y3WorkText` TEXT NULL;
